site_name: cs4414-main

theme:
  name: material
  #name: mkdocs
  # custom_dir: material

  # 404 page
  static_templates:
  - 404.html
    
  navigation_depth: 1
  
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: deep red
    accent: deep red
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
  # - git-revision-date-localized   # displaying the date of the last git modification of a page (require installation. will fail github workflow)

nav:
  - Syllabus: README.md
  - FAQ: faq.md